version: 0.2 # Đây là dòng bắt buộc và đúng định dạng cho buildspec.yml

phases:
  install:
    runtime-versions:
      python: 3.11 # Đảm bảo runtime này khớp với các hàm Lambda của bạn
    commands:
      - pip install aws-sam-cli # Cài đặt AWS SAM CLI
  build:
    commands:
      - echo "Bắt đầu giai đoạn build của SAM..."
      # Lệnh 'sam build' sẽ đóng gói mã nguồn và dependencies của các hàm Lambda
      - sam build --template template.yml --use-container # Sử dụng template.yml để build

  post_build:
    commands:
      - echo "Bắt đầu giai đoạn triển khai (deploy) SAM..."
      # Thay thế 'fcj-book-shop-deployment-stack' bằng tên stack mong muốn của bạn.
      # Thay thế 'YOUR_S3_BUCKET_FOR_SAM_DEPLOYMENT' bằng tên S3 bucket duy nhất của bạn
      # (mà bạn phải tự tạo trước đó, chỉ dùng cho việc deploy artifact).
      - sam deploy --template-file .aws-sam/build/template.yaml --stack-name fcj-book-store --s3-bucket S3_BUCKET_FOR_SAM_DEPLOYMENT --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --no-confirm-changeset
      - echo "Triển khai hoàn tất!"

artifacts:
  files:
    - '**/*' # Bao gồm tất cả các file được tạo ra trong quá trình build
  base-directory: .aws-sam/build # Nơi SAM CLI đặt các artifact đã build